### ISSUE TITLE
links seem to be off?

### ISSUE THREAD

**Issue by jbenet** [ipfs/gateway-dmca-denylist#5]
links on https://ipfs.io/refs/ seem to be off-- the `lists` link is linking to `href=/lists` instead of `href=lists`. not sure if this is a go-ipfs problem or a refs.ipfs.io problem

**Comment by ghost** [comment]
Yeah we need to fix the gateway: https://github.com/ipfs/go-ipfs/issues/1955

Had similar issues when we added the IPNS hostname support.

**Comment by jbenet** [comment]
oh whoops. didnt see that
